import { config } from "dotenv";
config({ path: ".env.local", quiet: true });
import { createAdminClient } from "./supabaseAdmin";

// One-time cleanup of the canonical `ingredients` table, reviewed by hand
// against each entry's recipe_ingredients.raw_text (not generated by an LLM
// call — dumped from the DB, read, and decided on manually). Fixes three
// kinds of accumulated cruft:
//   - RENAME_MAP: garbled leftovers of a failed quantity/unit parse (e.g.
//     "or 2 scallions", "to 10 dumplings") corrected to the real ingredient
//     name, plus singular/plural duplicates ("scallions" -> "scallion")
//     collapsed to one canonical form. If the target name already exists as
//     a different ingredient, this is a merge (recipe_ingredients and
//     grocery_list_items repointed, the source row deleted); otherwise it's
//     an in-place rename. name_fr is cleared on rename so `npm run
//     translate` retranslates it.
//   - FLAG_NAMES: not ingredients at all (recipe notes/instructions/titles
//     a scrape mistakenly captured as an ingredient line) — reported only,
//     never auto-deleted, since removing the row would also drop its
//     raw_text with no way to recover it short of a re-scrape.
//   - DELETE_NAMES: canonical rows with zero referencing recipe_ingredients
//     or grocery_list_items rows already (dead data, e.g. from a recipe
//     that was later removed) — deleted outright after verifying the
//     reference count really is zero.

const RENAME_MAP: Record<string, string> = {
  // --- singular/plural + punctuation duplicates ---
  "apples": "apple",
  "avocados": "avocado",
  "bananas": "banana",
  "boiled eggs": "boiled egg",
  "boneless, skinless chicken breasts": "boneless, skinless chicken breast",
  "boneless, skinless chicken thighs": "boneless, skinless chicken thigh",
  "carrots": "carrot",
  "chicken thighs": "chicken thigh",
  "chili peppers": "chili pepper",
  "chopped scallions": "chopped scallion",
  "cinnamon sticks": "cinnamon stick",
  "cucumbers": "cucumber",
  "dashi packets": "dashi packet",
  "dumplings": "dumpling",
  "eggs": "egg",
  "fried eggs": "fried egg",
  "Fuji apples": "Fuji apple",
  "gallon airtight container or jar.": "gallon airtight container or jar",
  "gelatin sheets": "gelatin sheet",
  "gochugaru,": "gochugaru",
  "green chili peppers": "green chili pepper",
  "green or red chili peppers": "green or red chili pepper",
  "hard-boiled eggs": "hard-boiled egg",
  "Japanese eggplants": "Japanese eggplant",
  "Japanese or Chinese eggplants": "Japanese or Chinese eggplant",
  "Japanese or Persian cucumbers": "Japanese or Persian cucumber",
  "Japanese turnips": "Japanese turnip",
  "king oyster mushrooms": "king oyster mushroom",
  "kiwis": "kiwi",
  "Korean cucumbers": "Korean cucumber",
  "large eggs": "large egg",
  "large egg whites": "large egg white",
  "large egg yolks": "large egg yolk",
  "large scallions": "large scallion",
  "leeks": "leek",
  "limes": "lime",
  "lotus roots": "lotus root",
  "mandarin oranges": "mandarin orange",
  "matsutake mushrooms": "matsutake mushroom",
  "medium carrots": "medium carrot",
  "medium napa cabbages": "medium napa cabbage",
  "medium onions": "medium onion",
  "medium size Korean/Asian eggplants": "medium size Korean/Asian eggplant",
  "Meyer lemons": "Meyer lemon",
  "minced garlic,": "minced garlic",
  "mu,": "mu",
  "navel oranges": "navel orange",
  "onions": "onion",
  "oranges": "orange",
  "oxtails": "oxtail",
  "Persian cucumbers": "Persian cucumber",
  "pickles": "pickle",
  "plump garlic cloves": "plump garlic clove",
  "prawns": "prawn",
  "red chili peppers": "red chili pepper",
  "red onions": "red onion",
  "ripe bananas": "ripe banana",
  "scallions": "scallion",
  "scallions,": "scallion",
  "scallion white parts": "scallion white part",
  "sesame seeds": "sesame seed",
  "shallots": "shallot",
  "shiitake mushrooms": "shiitake mushroom",
  "shrimps": "shrimp",
  "skin-on salmon fillets": "skin-on salmon fillet",
  "small carrot,": "small carrot",
  "small carrots": "small carrot",
  "small onion,": "small onion",
  "soft or hard-boiled eggs": "soft or hard-boiled egg",
  "thin ginger slices": "thin ginger slice",
  "thymes": "thyme",
  "unagi fillets": "unagi fillet",
  "yuzu peels": "yuzu peel",
  "zucchinis": "zucchini",

  // --- garbled leftovers of a failed quantity/unit/range parse ---
  "servings cooked Japanese short-grain rice": "cooked Japanese short-grain rice",
  "1-thick steak": "steak",
  "rice cooker cup sweet rice/glutinous rice": "sweet rice",
  "servings cooked Japanese short-grain rice ( )": "cooked Japanese short-grain rice",
  "large large eggs": "large egg",
  "rice cooker cups uncooked Japanese short-grain white rice": "uncooked Japanese short-grain white rice",
  "servings cooked Japanese short-grain brown rice ( )": "cooked Japanese short-grain brown rice",
  "rice cooker cup uncooked Japanese short-grain white rice": "uncooked Japanese short-grain white rice",
  "zest of 2 lemons": "lemon zest",
  "M1nute Miso": "Minute Miso",
  "QT room temperature or cold filtered water": "room temperature or cold filtered water",
  "rice bowl cooked Japanese short-grain rice": "cooked Japanese short-grain rice",
  "can whole peeled or crushed tomato and juice": "whole peeled or crushed tomato and juice",
  "servings veggies/mushrooms of your choice": "veggies/mushrooms of your choice",
  "or 6 thin scallions": "thin scallions",
  "salt to taste – about 1/4 teaspoon": "salt",
  "or 2 scallion white parts": "scallion white part",
  "or 2 teaspoons sugar": "sugar",
  "plus 1 teaspoon sugar": "sugar",
  "to 1 tablespoon gochugaru": "gochugaru",
  "cornstarch mixed in 2 tablespoons water": "cornstarch",
  "scallions, cut into 2 inch pieces": "scallion",
  "or 3 caps shiitake mushrooms": "shiitake mushroom",
  "gochugaru , Korean red chili pepper flakes": "gochugaru",
  "Korean cucumber or 2 Kirby": "Korean cucumber or 2 Kirby cucumbers",
  "dried pat about 2 cups": "dried pat",
  "about 1/2 of a medium Korean/Asian pear grated": "Korean/Asian pear",
  "about 1/2 of a medium onion grated": "onion",
  "or 2 tablespoons gochugaru": "gochugaru",
  "of 1 package raw ramen noodles": "raw ramen noodles",
  "kabocha or small pumpkin, about 2 pounds": "kabocha or small pumpkin",
  "ginger piece or 1 teaspoon minced": "ginger",
  "large onion, roughly cut into small pieces": "large onion",
  "large apple, roughly cut into small pieces": "large apple",
  "plump garlic cloves, roughly cracked oped": "plump garlic clove",
  "or 4 dried shiitake mushrooms": "dried shiitake mushrooms",
  "thin ginger slices, about 1-inch round": "thin ginger slice",
  "medium to large goguma , Korean sweet potatoes": "Korean sweet potato",
  "scallions, cut into 2-inch pieces": "scallion",
  "small apple grated, 3": "apple",
  "or 2 scallions": "scallion",
  "thin slices Spam or 2 tablespoons canned tuna": "Spam or canned tuna",
  "tender inner parts of 1 napa cabbage, salted": "napa cabbage, salted",
  "whole fresh pork belly about 3-inch wide cut": "pork belly",
  "instant coffee, or a cup of brewed coffee": "instant coffee or brewed coffee",
  "about 2 ounces dried chwinamul": "dried chwinamul",
  "or cucumber": "cucumber",
  "or 2 teaspoons gochujang or gochugaru": "gochujang or gochugaru",
  "to 2 cups assortment of seafood": "assortment of seafood",
  "or 2 bunches scallions": "scallion",
  "or 1.5 tablespoons finely chopped scallion": "chopped scallion",
  "or 1.5 tablespoons finely chopped carrot": "chopped carrot",
  "doenjang, 된장, Korean fermented soybean paste": "doenjang",
  "a 3/4": "gallon airtight container or jar",
  "shredded cheese or 2 slices": "shredded cheese",
  "kirby cucumber or 1/2 Korean cucumber": "kirby cucumber or Korean cucumber",
  "or 4 shiitake mushrooms": "shiitake mushroom",
  "gochujang , Korean red chili pepper paste": "gochujang",
  "about 18-oz pack firm tofu": "firm tofu",
  "thin half-moon shape slices of a Korean pear": "Korean pear",
  "juice of 1/2 of a fresh lemon": "lemon juice",
  "sugar or 2 tablespoons maesilcheong": "sugar or maesilcheong",
  "or 3 scallions": "scallion",
  "plus 1 or 2 teaspoons boiling hot water": "boiling hot water",
  "or 2 tablespoons soy sauce": "soy sauce",
  "medium or 4 small blue crabs": "blue crabs",
  "or 2 green and/or red chili peppers": "green and/or red chili peppers",
  "red chili pepper or 1/4 red bell pepper": "red chili pepper or red bell pepper",
  "or 2 bay leaves": "bay leaves",
  "Korean red chili pepper flakes, gochugaru": "gochugaru",
  "about 3 pounds short ribs": "short ribs",
  "medium carrots, about 5 ounces": "medium carrot",
  "dasima , about 3-inch square": "dasima",
  "green cabbage, yangbaechu up to 4 ounces": "green cabbage",
  "shredded cheese or more to taste -- optional": "shredded cheese",
  "or 1.5 tablespoons gochujang": "gochujang",
  "or 2 tablespoons hot sauce": "hot sauce",
  "or 2 teaspoons oyster sauce": "oyster sauce",
  "small apple , cut into thin, small slices": "small apple",
  "scallions cut into 2-inch pieces": "scallion",
  "thin ginger slices, about 1 inch rounds": "thin ginger slice",
  "or 2 scallions, roughly chopped": "chopped scallion",
  "sugar or 2-3 teaspoons maesilcheong 매실청": "sugar or maesilcheong",
  "strips pre-cut pickled radish strips, white or yellow": "pre-cut pickled radish strips, white or yellow",
  "or 2 dried shiitake or other mushrooms": "dried shiitake or other mushrooms",
  "dried red chili peppers or 1 teaspoon peppercorns": "dried red chili peppers or peppercorns",
  "or 4 scallions": "scallion",
  "white parts of 2 scallions": "scallion white part",
  "spinach, about 8 ounces": "spinach",
  "small cucumbers, about 5 ounces": "small cucumber",
  "or scallions": "scallion",
  "small Korean sweet potato , about 6 ounces": "Korean sweet potato",
  "perilla leaves, kkaennip, 깻잎, roughly sliced": "perilla leaves, roughly sliced",
  "or a handful of spring mix or arugula": "spring mix or arugula",
  "to 1/2 teaspoon cinnamon powder": "cinnamon powder",
  "to 3/4 cup hot water, about 170°F": "hot water",
  "or 2 sheets fish cake": "fish cake",
  "x 3 inches dried kelp": "dried kelp",
  "minced garlic, 8-9 plump cloves": "minced garlic",
  "grated ginger, about 1-inch thumb size": "grated ginger",
  "or 7 pine nuts per serving": "pine nuts",
  "jujube, seeded, rolled and sliced per serving": "jujube, seeded, rolled and sliced",
  "or 3 medium size": "abalone",
  "or 2 dried whole red chili peppers": "dried whole red chili peppers",
  "about 2 ounces pine needles": "pine needles",
  "glutinous rice flour, cooked in 1/2 cup of water": "glutinous rice flour",
  "about 2 teaspoons vegetable oil": "vegetable oil",
};

// Recipe notes/instructions/titles that a scrape mistakenly captured as an
// ingredient line. Reported for manual review, never auto-deleted.
const FLAG_NAMES = [
  "Black Sesame Dan Dan Noodles",
  "Makes 7 to 9 about 3-inch fritters",
  "Double this if you want to serve with a sauce.",
  "Makes about 40 dumplings",
  "Makes 16 pieces",
  "Visit the links provided above for the ingredients for each soup.",
  "Visit the links provided above for the ingredients for each recipe.",
  "If the sauce is too thick, use a tablespoon of water or soda to thin it.",
  "Mix all sauce ingredients well and set aside.",
  "Makes 2 large pancakes or 6 small ones",
  "Pork Shabu Shabu and Cold Somen with Sesame Miso Sauce",
  "Dissolve 1/2 cup coarse salt in 4 cups of water, and soak the cabbage leaves until softened, 2 to 4 hours. Rinse and drain well.",
];

// Already unreferenced by any recipe_ingredients/grocery_list_items row
// (dead data — verified again at run time before deleting).
const DELETE_NAMES = [
  "-3 lotus root",
  "to 2.5 pounds fresh white fish fillets",
  "to 12 Korean white cucumbers",
  "to 3 cups sliced rice cakes",
  "to 10 dumplings",
  "to 5 pounds or about 15 small to medium young radishes with leaves",
  "/4 cups all purpose flour",
  "- ⅓ cup water",
];

interface Args {
  dryRun: boolean;
}

function parseArgs(): Args {
  return { dryRun: process.argv.includes("--dry-run") };
}

async function main() {
  const args = parseArgs();
  const admin = createAdminClient();

  const PAGE_SIZE = 1000;
  const nameToId = new Map<string, string>();
  for (let from = 0; ; from += PAGE_SIZE) {
    const { data, error } = await admin
      .from("ingredients")
      .select("id, name")
      .range(from, from + PAGE_SIZE - 1);
    if (error) throw new Error(`select ingredients failed: ${error.message}`);
    for (const ing of data ?? []) nameToId.set(ing.name, ing.id);
    if (!data || data.length < PAGE_SIZE) break;
  }

  let renamed = 0;
  let merged = 0;
  let failed = 0;

  for (const [oldName, newName] of Object.entries(RENAME_MAP)) {
    const id = nameToId.get(oldName);
    if (!id) {
      console.warn(`  skip: "${oldName}" not found (already fixed or renamed?)`);
      continue;
    }

    const collisionId = nameToId.get(newName);
    const isMerge = collisionId !== undefined && collisionId !== id;
    const label = `"${oldName}" -> "${newName}"${isMerge ? " (merge)" : ""}`;

    if (args.dryRun) {
      console.log(label);
      if (isMerge) merged++;
      else renamed++;
      continue;
    }

    try {
      if (isMerge) {
        const targetId = collisionId!;
        const { error: e1 } = await admin
          .from("recipe_ingredients")
          .update({ ingredient_id: targetId })
          .eq("ingredient_id", id);
        if (e1) throw new Error(e1.message);
        const { error: e2 } = await admin
          .from("grocery_list_items")
          .update({ ingredient_id: targetId })
          .eq("ingredient_id", id);
        if (e2) throw new Error(e2.message);
        const { error: e3 } = await admin.from("ingredients").delete().eq("id", id);
        if (e3) throw new Error(e3.message);
        merged++;
      } else {
        const { error: e1 } = await admin
          .from("ingredients")
          .update({ name: newName, name_fr: null })
          .eq("id", id);
        if (e1) throw new Error(e1.message);
        nameToId.set(newName, id);
        renamed++;
      }
      console.log(label);
    } catch (err) {
      console.warn(`  failed: ${label}: ${(err as Error).message}`);
      failed++;
    }
  }

  let deleted = 0;
  for (const name of DELETE_NAMES) {
    const id = nameToId.get(name);
    if (!id) {
      console.warn(`  skip delete: "${name}" not found`);
      continue;
    }
    const { count: riCount } = await admin
      .from("recipe_ingredients")
      .select("id", { count: "exact", head: true })
      .eq("ingredient_id", id);
    const { count: gliCount } = await admin
      .from("grocery_list_items")
      .select("id", { count: "exact", head: true })
      .eq("ingredient_id", id);
    if ((riCount ?? 0) > 0 || (gliCount ?? 0) > 0) {
      console.warn(`  skip delete: "${name}" is still referenced (${riCount} recipe_ingredients, ${gliCount} grocery_list_items)`);
      continue;
    }
    if (args.dryRun) {
      console.log(`delete  "${name}"`);
      deleted++;
      continue;
    }
    const { error: delError } = await admin.from("ingredients").delete().eq("id", id);
    if (delError) {
      console.warn(`  failed to delete "${name}": ${delError.message}`);
      failed++;
      continue;
    }
    console.log(`deleted "${name}"`);
    deleted++;
  }

  console.log(
    `\nfix-ingredient-names: ${renamed} renamed, ${merged} merged, ${deleted} deleted, ${failed} failed${args.dryRun ? " (dry run — no writes)" : ""}`,
  );
  console.log(`${FLAG_NAMES.length} flagged as not real ingredients (needs manual review, not touched):`);
  for (const name of FLAG_NAMES) {
    const id = nameToId.get(name);
    console.log(`  ${id ?? "(not found)"}  ${JSON.stringify(name)}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
